<nav class="global" role="navigation">
  <ul class="global-sections" role="menubar">
    <li ><a class="logolink mc-logo" title="Media Commons" href="#"><span>Media Commons</span></a>
      <ul class="navitems">
        <li role="menuitem"> <a href="#">Frontpage</a> </li>
        <li role="menuitem"> <a href="#">In Media Res</a> </li>
        <li role="menuitem"> <a href="#">MediaCommons Press</a> </li>
        <li role="menuitem"> <a href="#">The New Everyday</a> </li>
        <li role="menuitem"> <a href="#">#Alt-Academy</a> </li>
      </ul>
    </li>
  </ul>
  <ul class="utils logged-in" role="menubar">
    <li role="menuitem" aria-haspopup="true"> <a href="#" class="login-link">Kathleen Fitzpatrick</a>
      <ul role="menu" aria-hidden="true" class="user-pref-area">
        <li role="menuitem"> <a href="#">Edit my account</a> </li>
        <li role="menuitem"> <a href="#">View my contributions</a> </li>
        <li role="menuitem"> <a href="#">View my bookmarks</a> </li>
        <li role="menuitem"> <a href="#">Logout</a> </li>
      </ul>
    </li>
  </ul>
</nav>