<header role="banner">
  <a href="#main-nav" class="skip-to-nav">Skip to Navigation</a>
  <button type="button" class="skip-arrow"></button>
  <h1><a href="http://mediacommons.futureofthebook.org/imr/" title="Home" rel="home" class="imr logo"><span>In Media Res</span></a></h1>
  <form role="search" action="/imr/2013/08/06/data-collection-television-and-twitter"  accept-charset="UTF-8" method="post" id="search-block-form" class="form search header">
    <label for="edit-search-block-form-1"><span>Search this site:</span></label>
    <fieldset>
      <input type="search" maxlength="128" name="search_block_form" id="edit-search-block-form-1" size="15" value="" title="Enter the terms you wish to search for." placeholder="Search&hellip;" class="form-text" />
      <input type="submit" name="op" id="edit-submit-2" value="&#xe016;"  class="form-submit search" />
      <input type="hidden" name="form_build_id" id="form-557ed34a66c4cb505955a9b7f85dd892" value="form-557ed34a66c4cb505955a9b7f85dd892"  />
      <input type="hidden" name="form_token" id="edit-search-block-form-form-token" value="78f5d7fa5d984995d90befe37926bf15"  />
      <input type="hidden" name="form_id" id="edit-search-block-form" value="search_block_form" />
    </fieldset>
  </form>
  <nav id="main-nav" class="nav main imr" role="navigation">
    <ul class="main imr" role="menubar">
      <li role="menuitem"> <a href="#">Home</a> </li>
      <li role="menuitem"> <a href="#">Recent Posts</a></li>
      <li role="menuitem"> <a href="#">Current Calls</a></li>
    </ul>
  </nav>
</header>